owner_id         = "099720109477"
ami_name         = "ubuntu/images/hvm-ssd/ubuntu-jammy-*"
instance_type    = "t2.micro"
aws_region       = "eu-central-1"
vpc_name         = "vpc"
keypair          = "ring-challenge-team-1"
public_subnet_a  = "pub-subnet"
private_subnet_a = "priv-subnet-1"