owner_id      = "099720109477"
ami_name      = "ubuntu/images/hvm-ssd/ubuntu-jammy-*"
instance_type = "t2.micro"
aws_region       = "eu-central-1"
vpc_name         = "ta-vpc"
keypair       = "talent-academy-ec2"
public_subnet_a  = "<public-a>"
private_subnet_a = "<private-a"