owner_id      = "099720109477"
ami_name      = "ubuntu/images/hvm-ssd/ubuntu-jammy-*"
instance_type = "t2.micro"
aws_region       = "eu-central-1"
vpc_name         = "Main VPC created through Terraform"
keypair       = "talent-academy-ec2"
public_subnet_a  = "Public Subnet 1"
private_subnet_a = "Private Subnet 1"
