---
- hosts: servers
  become: yes
  tasks:
    - name: Update the apt-get of the machine
      apt:
        update_cache: yes

    - name: Copy private key from local machine to the each server
      copy:
        src: "~/.ssh/ring-challenge-team-1"
        dest: "/home/ubuntu/.ssh/"

    - name: Copy script to first server
      copy:
        src: "./test/script.sh"
        dest: "/home/ubuntu/"
        mode: 0777

- hosts: servers_jemila
  become: yes
  tasks:
    - name: Git checkout
      git:
        repo: 'https://github.com/muhammetkoele/ring-number-challenge-team-1.git'
        dest: /home/ubuntu/repobranch
        version: julioaranajr
        single_branch: yes
        update: yes

    - name: Copy txt file to first server
      copy:
        src: "./test/number.txt"
        dest: "/home/ubuntu/"
        mode: 0777

- hosts: servers_julio
  become: yes
  tasks:
    - name: Git checkout
      git:
        repo: 'https://github.com/muhammetkoele/ring-number-challenge-team-1.git'
        dest: /home/ubuntu/repobranch
        version: leticia
        single_branch: yes
        update: yes

- hosts: servers_leticia
  become: yes
  tasks:
    - name: Copy txt file to first server
      copy:
        src: "./test/number.txt"
        dest: "/home/ubuntu/"
        mode: 0777

    - name: Git checkout
      git:
        repo: 'https://github.com/muhammetkoele/ring-number-challenge-team-1.git'
        dest: /home/ubuntu/repobranch
        version: muhammet
        single_branch: yes
        update: yes
    
    - name: Run script on the the third server
      shell: (cd /home/ubuntu; sh script.sh)
      become: yes
      become_user: ubuntu
      register: output 
    
    - name: Run a command using a templated variable (always use quote filter to avoid injection)
      ansible.builtin.debug: 
        msg: "third server, count: {{ output.stdout }}"
  
- hosts: servers_muhammet
  become: yes
  tasks:
    - name: Git checkout
      git:
        repo: 'https://github.com/muhammetkoele/ring-number-challenge-team-1.git'
        dest: /home/ubuntu/repobranch
        version: rima
        single_branch: yes
        update: yes

- hosts: servers_rima
  become: yes
  tasks:
    - name: Git checkout
      git:
        repo: 'https://github.com/muhammetkoele/ring-number-challenge-team-1.git'
        dest: /home/ubuntu/repobranch
        version: jemila
        single_branch: yes
        update: yes