---
- hosts: servers
  become: yes
  tasks:
    - name: Update the apt-get of the machine
      apt:
        update_cache: yes

    - name: Copy private key from local machine to the each server
      copy:
        src: "~/.ssh/ring-challenge-team-1"
        dest: "/home/ubuntu/.ssh/"

    - name: Copy script to first server
      copy:
        src: "./test/script.sh"
        dest: "/home/ubuntu/"
        mode: 0777

- hosts: servers_jemila
  become: yes
  tasks:
    - name: Copy txt file to first server
      copy:
        src: "./test/number.txt"
        dest: "/home/ubuntu/"
        mode: 0777

- hosts: servers
  become: yes
  tasks:
    - name: Git checkout
      git:
        repo: 'https://github.com/muhammetkoele/ring-number-challenge-team-1.git'
        dest: /home/ubuntu/repobranch
        version: "{{ item }}"
        single_branch: yes
        update: yes
        loop:
          - julioaranajr
          - leticia
          - muhammet
          - rima
          - jemila
    - name: Run CRON job to run script at every minute. 
      cron: 
        name: “run script"
        user: "ubuntu"
        weekday: "*"
        minute: "*"
        hour: "*"
        job: "sh /home/ubuntu/script.sh"
        state: present