---
- hosts: servers
  become: yes
  tasks:
    - name: Update the apt-get of the machine
      apt:
        update_cache: yes

    - name: Copy private key from local machine to the each server
      copy:
        src: "~/.ssh/ring-challenge-team-1"
        dest: "/home/ubuntu/.ssh/"
